file(READ "${INPUT_FILE}" contents)
string(CONFIGURE "${contents}" contents @ONLY)
if(EXISTS "${OUTPUT_FILE}")
    file(READ "${OUTPUT_FILE}" contents_prev)
    if(contents STREQUAL contents_prev)
        return()
    endif()
endif()
file(WRITE "${OUTPUT_FILE}" "${contents}")
